import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ThemeProvider } from 'next-themes';
import Header from '@components/Header/Header';
import ReactScan from '@components/ReactScan/ReactScan';
import './globals.scss';

const enFont = localFont({
  src: './fonts/PTSans-Regular.ttf',
  display: 'swap',
  variable: '--font-roboto',
});

const chineseFont = localFont({
  src: './fonts/ChocolateClassicalSans-Regular.ttf',
  display: 'swap',
  variable: '--font-noto-tc',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW" className={`${enFont.variable} ${chineseFont.variable}`} suppressHydrationWarning>
      <ReactScan />
      <body>
        <ThemeProvider enableSystem disableTransitionOnChange>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
